/// <reference path="../src/index.d.ts" />
import State from './state';
import * as util from './utils';
export { IMPERIAL, METRIC } from './constants';
export declare const state: State;
export declare const units: (units: import("./constants").Unit) => void;
export declare const tool: (tool: number) => void;
export declare const resolution: (resolution: number) => void;
export declare const feed: (feedRate: number) => void;
export declare const speed: (speed: number) => void;
export declare const cut: (coordinate: import("./coordinate").default) => void;
export declare const icut: (offset: import("./coordinate").default) => void;
export declare const rapid: (coordinate: import("./coordinate").default) => void;
export declare const irapid: (offset: import("./coordinate").default) => void;
export declare const dwell: (duration: number) => void;
export declare const rotate: (angle: number, cb?: (() => void) | undefined) => void;
export declare const scale: (scales: number | import("./coordinate").default, cb?: (() => void) | undefined) => void;
export declare const translate: (offset: import("./coordinate").default, cb?: (() => void) | undefined) => void;
export declare const arc: (centerOffset: import("./coordinate").default, angle: number, plane?: "XY" | "XZ" | "YZ" | undefined) => void;
export declare const radiusArc: (radius: number, startAngle: number, endAngle: number, plane?: "XY" | "XZ" | "YZ" | undefined) => void;
export declare const ellipse: (radiusX: number, radiusY: number, offsetZ: number | undefined, angle: number, angleStart?: number | undefined, points?: number | undefined, plane?: "XY" | "XZ" | "YZ" | undefined) => void;
export declare const save: (path: string) => void;
export declare const log: () => void;
export declare const reset: () => void;
export declare const utils: typeof util;
export declare function gcode(): string[][];
export declare function helix(radius: number, depth: number, depthPerCut: number, zSafe: number): void;
export declare function drill(depth: number, depthPerCut: number, zSafe: number): void;
export declare function view(containerEl?: HTMLElement): void;
