import Coordinate from './coordinate';
export declare const axes: string[];
export declare function sumCoords(coord1: Coordinate, coord2: Coordinate): Coordinate;
export declare function toRadians(angle: number): number;
export declare function toDegrees(radians: number): number;
export declare function findCoordOnCircle(radius: number, angle: number, offset: Coordinate): Coordinate;
export declare function mergeCoords(coord1: Coordinate, coord2: Coordinate): Coordinate;
export declare function round(number: number, precision?: number): number;
export declare function roundCoord(coord: Coordinate, precision?: number): Coordinate;
export declare function coordToString(coord: Coordinate): string;
